# -*- mode: ruby -*-                                                                                                           
# vi: set ft=ruby :                                                                                                            

Vagrant.configure("2") do |config|

  ## powershell                                                                                                                                                     
  # net use z: \\VBOXSVR\vagrant                                                                                                                                    
  # C:\Windows\System32\cmd.exe /k %windir%\System32\reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f   
  # msiexec /i node-v6.11.3-x64.msi /qn                                                                                                                             
  # Git-2.14.1-64-bit.exe /silent                                                                                                                                   

  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_check_update = false

  config.vm.guest = :windows
  config.vm.communicator = :ssh
  config.ssh.insert_key = false
  config.ssh.username = 'IEUser'
  config.ssh.password = 'Passw0rd!'

  config.vm.provider "virtualbox" do |vbox|
  	vbox.name = "Win10"
    vbox.gui = true
    vbox.cpus = 2
    vbox.memory = 4096
    vbox.customize ["modifyvm", :id, "--vram", "256"]
    vbox.customize ['modifyvm', :id, '--accelerate2dvideo', 'on']
    vbox.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

 config.vm.provision "file", source: "README.md", destination: "README.md"



end

